package com.theforum.entities;
// Generated Feb 18, 2018 12:44:44 PM by Hibernate Tools 4.3.1.Final

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.theforum.util.DateUtils;

/**
 * Forums generated by hbm2java
 */
@Entity
@Table(name = "forums", catalog = "myforumweb")
public class Forums implements java.io.Serializable {

	private long forumId;
	private String forumDescription;
	private Integer forumOrder;
	private String forumName;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "forum_createdate", length = 19)
	private Date forumCreatedate;
	private String forumPic;
	

	private List<Topics> topicses = new ArrayList<Topics>(0);

	
	

	public Forums() {
		
		setForumCreatedate(DateUtils.parseDate(LocalDate.now().toString()));
		setForumPic("assets/img/default_forum_pic.png");
		setForumOrder(100);
		
	}

	public Forums(long forumId) {
		this.forumId = forumId;
	}

	public Forums(long forumId, String forumDescription, Integer forumOrder, String forumName, List<Topics> topicses) {
		this.forumId = forumId;
		this.forumDescription = forumDescription;
		this.forumOrder = forumOrder;
		this.forumName = forumName;
		this.topicses = topicses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "forum_id", unique = true, nullable = false)
	public long getForumId() {
		return this.forumId;
	}

	public void setForumId(long forumId) {
		this.forumId = forumId;
	}

	@Column(name = "forum_description")
	public String getForumDescription() {
		return this.forumDescription;
	}

	public void setForumDescription(String forumDescription) {
		this.forumDescription = forumDescription;
	}

	@Column(name = "forum_order")
	public Integer getForumOrder() {
		return this.forumOrder;
	}

	public void setForumOrder(Integer forumOrder) {
		this.forumOrder = forumOrder;
	}

	@Column(name = "forum_name")
	public String getForumName() {
		return this.forumName;
	}

	public void setForumName(String forumName) {
		this.forumName = forumName;
	}
	
	public Date getForumCreatedate() {
		return forumCreatedate;
	}

	public void setForumCreatedate(Date forumCreatedate) {
		this.forumCreatedate = forumCreatedate;
	}

	public String getForumPic() {
		return forumPic;
	}

	public void setForumPic(String forumPic) {
		this.forumPic = forumPic;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "forums")
	public List<Topics> getTopicses() {
		return this.topicses;
	}

	public void setTopicses(List<Topics> topicses) {
		this.topicses = topicses;
	}


}
