package com.theforum.entities;
// Generated Feb 18, 2018 12:44:44 PM by Hibernate Tools 4.3.1.Final

import java.time.LocalDate;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.theforum.util.DateUtils;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts", catalog = "myforumweb")
public class Posts implements java.io.Serializable {

	private long postId;
	private Forums forums;
	private Topics topics;
	private Users users;
	private Date postDate;
	private String postSubject;
	private String postText;

	public Posts() {
		setPostDate(DateUtils.parseDate(LocalDate.now().toString()));
	}

	public Posts(long postId) {
		this.postId = postId;
	}

	public Posts(long postId, Forums forums, Topics topics, Users users, Date postDate, String postSubject,
			String postText) {
		this.postId = postId;
		this.forums = forums;
		this.topics = topics;
		this.users = users;
		this.postDate = postDate;
		this.postSubject = postSubject;
		this.postText = postText;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "post_id", unique = true, nullable = false)
	public long getPostId() {
		return this.postId;
	}

	public void setPostId(long postId) {
		this.postId = postId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "forum_id")
	public Forums getForums() {
		return this.forums;
	}

	public void setForums(Forums forums) {
		this.forums = forums;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "topic_id")
	public Topics getTopics() {
		return this.topics;
	}

	public void setTopics(Topics topics) {
		this.topics = topics;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_date", length = 19)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "post_subject")
	public String getPostSubject() {
		return this.postSubject;
	}

	public void setPostSubject(String postSubject) {
		this.postSubject = postSubject;
	}

	@Column(name = "post_text")
	public String getPostText() {
		return this.postText;
	}

	public void setPostText(String postText) {
		this.postText = postText;
	}

}
