package com.theforum.entities;
// Generated Feb 18, 2018 12:44:44 PM by Hibernate Tools 4.3.1.Final

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.theforum.util.DateUtils;

/**
 * Topics generated by hbm2java
 */
@Entity
@Table(name = "topics", catalog = "myforumweb")
public class Topics implements java.io.Serializable {

	private long topicId;
	private Forums forums;
	private Users users;
	private Date topicDate;
	private String topicSubject;
	private String topicBody;
	private List<Posts> postses = new ArrayList<Posts>(0);
	private int topicWatcherNumber;
	private int topicCommentNumber;
	
	public Topics() {
		setTopicDate(DateUtils.parseDate(LocalDate.now().toString()));
	}

	public Topics(long topicId) {
		this.topicId = topicId;
	}

	public Topics(long topicId, Forums forums, Users users, Date topicDate, String topicSubject, String topicBody, List<Posts> postses) {
		this.topicId = topicId;
		this.forums = forums;
		this.users = users;
		this.topicDate = topicDate;
		this.topicSubject = topicSubject;
		this.topicBody =topicBody;
		this.postses = postses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "topic_id", unique = true, nullable = false)
	public long getTopicId() {
		return this.topicId;
	}

	public void setTopicId(long topicId) {
		this.topicId = topicId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "forum_id")
	public Forums getForums() {
		return this.forums;
	}

	public void setForums(Forums forums) {
		this.forums = forums;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "topic_date", length = 19)
	public Date getTopicDate() {
		return this.topicDate;
	}

	public void setTopicDate(Date topicDate) {
		this.topicDate = topicDate;
	}

	@Column(name = "topic_subject")
	public String getTopicSubject() {
		return this.topicSubject;
	}

	public void setTopicSubject(String topicSubject) {
		this.topicSubject = topicSubject;
	}
	
	@Column(name = "topic_sbody")
	public String getTopicBody() {
		return this.topicBody;
	}

	public void setTopicBody(String topicBody) {
		this.topicBody = topicBody;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "topics")
	public List<Posts> getPostses() {
		return this.postses;
	}

	public void setPostses(List<Posts> postses) {
		this.postses = postses;
	}
	
	@Column(name = "topic_watcher_number")
	public int getTopicWatcherNumber() {
		return topicWatcherNumber;
	}
	
	public void setTopicWatcherNumber(int topicWatcherNumber) {
		this.topicWatcherNumber = topicWatcherNumber;
	}
	
	@Column(name = "topic_comment_number")
	public int getTopicCommentNumber() {
		return topicCommentNumber;
	}

	public void setTopicCommentNumber(int topicCommentNumber) {
		this.topicCommentNumber = topicCommentNumber;
	}
	

	
	
}
